apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: default
  name: eureka
  labels:
    app: eureka
spec:
  serviceName: "eureka"
  replicas: 3
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      labels:
        app: eureka
    spec:
      terminationGracePeriodSeconds: 10
      imagePullSecrets:
        - name: my-registry-key
      containers:
        - name: eureka
          image: eureka-server:v1
          ports:
            - containerPort: 8761
            - containerPort: 7761
          env:
            - name: EUREKA_INSTANCE_HOST_NAME
              value: ${HOSTNAME}.eureka
            - name: EUREKA_INSTANCE_LIST
              value: "http://eureka-0.eureka.default.svc.cluster.local:8761/eureka/,http://eureka-1.eureka.qcbm.svc.cluster.local:8761/eureka/,http://eureka-2.eureka.qcbm.svc.cluster.local:8761/eureka/"

          # 健康检查
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 7761
            initialDelaySeconds: 20
            timeoutSeconds: 5
